import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-w-2xl mx-auto p-10'>
        <header className="bg-gray-800 text-white mb-2">
          <div className="container mx-auto px-4 py-6 flex justify-between items-center">
            <div>
            <h1 className="text-2xl font-semibold">Henry Schein Wan Kandobi Search Wars</h1>
            <h2 className="text-xl italic"> The Dental Force Awakens</h2>
            </div>
            <nav>

            </nav>
          </div>
        </header>
        <div>
          {children}
        </div>
        </div>
      </body>
    </html>
  )
}
